# netlify.toml

[build]
  publish = "build"  # Adjust based on where your built files are located
  command = "npm run build"  # Adjust the build command as per your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
